version: "3.1"

services:
  eureka-server1:
    image: taskbeez/eureka-server:master
    environment:
      - spring.profiles.active=eureka-server1
    volumes:
      - .:/application
    ports:
      - 8761:8761
    networks:
      - eureka-net
    restart: always

networks:
  eureka-net:
    driver: bridge
